// Chatbot Version 7 knowledge — french / jokes
// Extracted from Version 6.7. Rule order is preserved globally.

window.registerKnowledgeRule({ order: 894, language: "french", category: "jokes", run: function(lowerMessage, userMessage, lang) {
  if (lowerMessage.includes("audubon") &&
  !lowerMessage.includes("photo")) {
  return "John James Audubon was an American naturalist, painter, and ornithologist best known for his detailed and vivid illustrations of North American birds. Born in Haiti on April 26, 1785, Audubon was raised in France before moving to the United States at a young age. His works are regarded as some of the most significant contributions to the field of natural history and are celebrated for their artistic quality as well as their scientific accuracy.<br><br>Audubon’s passion for nature began early in life. After trying various professions—including business, which he was not successful in—he decided to dedicate himself to studying and documenting the wildlife of North America. His major work, *The Birds of America*, is often considered one of the finest ornithological works ever completed. The book, first published between 1827 and 1838, contains 435 life-sized, hand-colored engravings of North American birds. Audubon traveled extensively to observe birds in their natural habitats, often braving difficult and dangerous conditions to capture the beauty of these creatures.<br><br>Audubon’s illustrations were groundbreaking in their accuracy and realism. Unlike many of his contemporaries, he didn't rely on taxidermied specimens but instead observed birds in the wild, capturing them in their natural poses and behaviors. His work also reflected his deep respect for nature, with each bird shown in its environment, often with vivid landscapes in the background.<br><br>Though Audubon is most famous for his bird illustrations, he was also a talented painter of mammals, reptiles, and plants. His attention to detail and artistic skill set him apart from other naturalists and illustrators of the time. However, Audubon faced significant financial struggles throughout his career. His major works were often funded by wealthy patrons or through expensive subscriptions, and he spent much of his life in debt.<br><br>Despite his challenges, Audubon’s legacy has endured. His contributions to ornithology were groundbreaking, and his art continues to inspire both scientists and artists. The *Audubon Society*, founded in 1905, is dedicated to the conservation of birds and their habitats, further cementing Audubon’s lasting impact on environmental science.<br><br>Audubon died on January 27, 1851, but his work remains a symbol of the intersection between art, science, and a deep appreciation for the natural world.<br><br><img src='https://www.pbs.org/wnet/americanmasters/files/2008/08/610_audubon_timeline.jpg' width='200'><br><br><img src='https://beforetheart.wordpress.com/wp-content/uploads/2013/09/h015-001.jpg?w=584&h=704' width='200'>";
  }
  return undefined;
}});
