// Chatbot Version 7 knowledge — spanish / jokes
// Extracted from Version 6.7. Rule order is preserved globally.

window.registerKnowledgeRule({ order: 450, language: "spanish", category: "jokes", run: function(lowerMessage, userMessage, lang) {
  if (lowerMessage.includes("timbuktu")) {
  return "Timbuktu is a historic city located in the West African nation of Mali, situated on the edge of the Sahara Desert near the Niger River. Once a prominent center of trade, culture, and education, it holds a significant place in both African and world history.<br><br>Timbuktu became a major hub of commerce and scholarship during the 15th and 16th centuries, especially under the rule of the Mali Empire. It was known for its wealth, primarily generated from trade in gold, salt, and other goods, which passed through the city due to its strategic location along trans-Saharan trade routes.<br><br>What made Timbuktu particularly unique was its reputation as a center of learning and culture. The city was home to some of the world’s oldest and most renowned universities, particularly during the reign of the Mali Empire. The University of Sankore, established in the 14th century, attracted scholars from across the Muslim world. Timbuktu was known for its vast libraries filled with manuscripts covering subjects like astronomy, mathematics, history, and religion, many of which were written in Arabic.<br><br>Timbuktu was a key player in the spread of Islamic knowledge and culture throughout West Africa. It was also a crossroads for many different cultures, bringing together Berber, Arab, and African traditions. This melting pot made Timbuktu a vital cultural and intellectual center, and it flourished as one of the great cities of the medieval world.<br><br>Over time, however, Timbuktu's importance declined. By the 17th century, the city faced invasions and political instability. Despite this, it remained a symbol of African heritage, with many of its ancient manuscripts surviving the centuries. Unfortunately, recent political unrest and armed conflict in Mali have put these historical treasures at risk, though efforts to preserve and protect Timbuktu's cultural heritage continue.<br><br>Today, Timbuktu is a UNESCO World Heritage site, with its ancient mosques, libraries, and manuscripts drawing interest from historians, archaeologists, and travelers alike. While the city is far from the bustling intellectual and economic hub it once was, it remains an enduring symbol of Africa's rich historical and cultural legacy.<br><br>Timbuktu’s legacy as a center of knowledge and its role in the trans-Saharan trade make it a significant part of world history, representing a rich chapter in the development of both African and global civilizations.<br><br><img src='https://media.cnn.com/api/v1/images/stellar/prod/120412050115-sankore-mosque-timbuktu.jpg?q=w_4096,h_2742,x_0,y_0,c_fill' width='200'><br><br><img src='https://images.nationalgeographic.org/image/upload/v1652341437/EducationHub/photos/timbuktu.jpg' width='200'>";
  }
  return undefined;
}});
